src/main/default/objects/Test_Data_Factory_Default__mdt/Test_Data_Factory_Default__mdt.object-meta.xml
<CustomObject>
    <description>Configure default values for SObject Factories and Scenarios.
These default values work even when SObjectFactory and SObjectFactoryScenario are not implemented.
Note that these values can be overwritten by createDefaults method.</description>
    <label>Test Data Factory Default</label>
    <pluralLabel>Test Data Factory Defaults</pluralLabel>
</CustomObject>

src/main/core/objects/Test_Data_Factory_Default__mdt/fields/Active_for_Custom_Factory__c.field-meta.xml
<CustomField>
    <fullName>Active_for_Custom_Factory__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This default value will be used when an SObject Factory is implemented.</description>
    <inlineHelpText>This default value will be used when an SObject Factory is implemented.</inlineHelpText>
    <label>Active for Custom Factory</label>
    <type>Checkbox</type>
</CustomField>

src/main/core/objects/Test_Data_Factory_Default__mdt/fields/Active_for_Default_Factory__c.field-meta.xml
<CustomField>
    <fullName>Active_for_Default_Factory__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This default value will be used when an SObject Factory is not implemented.</description>
    <inlineHelpText>This default value will be used when an SObject Factory is not implemented.</inlineHelpText>
    <label>Active for Default Factory</label>
    <type>Checkbox</type>
</CustomField>

src/main/core/objects/Test_Data_Factory_Default__mdt/fields/Active_for_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Active_for_Scenario__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This default value will be used when a SObjectFactoryScenario is used.</description>
    <inlineHelpText>This default value will be used when a SObjectFactoryScenario is used.</inlineHelpText>
    <label>Active for Scenario</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Test_Data_Factory_Default__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>65</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/core/objects/Test_Data_Factory_Default__mdt/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <description>The default value. The data type will be determined automatically based on the field API name.</description>
    <inlineHelpText>The default value. The data type will be determined automatically based on the field API name.</inlineHelpText>
    <label>Field Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Test_Data_Factory_Default__mdt/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <label>SObject API Name</label>
    <length>43</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/core/classes/TestDataFactoryDefaultSettingsTest.cls
/**
 * @author Ondrej Kratochvil
 * @date 2021-10-16
 */
@IsTest
private class TestDataFactoryDefaultSettingsTest {
    @IsTest
    static void testGetDefaults_activeForDefaultFactory() {
        TestDataFactoryDefaultSettings.sObjNameToSettings.put('Account', new List<Test_Data_Factory_Default__mdt>{
                new Test_Data_Factory_Default__mdt(
                        Active_for_Default_Factory__c = true,
                        Active_for_Scenario__c = false,
                        Active_for_Custom_Factory__c = false,
                        SObject_API_Name__c = 'Account',
                        Field_API_Name__c = 'Description',
                        Field_Value__c = 'desc'
                )
        });
        Account acc = (Account) TestDataFactoryDefaultSettings.getDefaults(Account.SObjectType, true, false);
        System.assertEquals('desc', acc.Description);
        acc = (Account) TestDataFactoryDefaultSettings.getDefaults(Account.SObjectType, false, false);
        System.assertEquals(null, acc.Description);
        acc = (Account) TestDataFactoryDefaultSettings.getDefaults(Account.SObjectType, false, true);
        System.assertEquals(null, acc.Description);
    }
    @IsTest
    static void testGetDefaults_activeForCustomFactory() {
        TestDataFactoryDefaultSettings.sObjNameToSettings.put('Account', new List<Test_Data_Factory_Default__mdt>{
                new Test_Data_Factory_Default__mdt(
                        Active_for_Default_Factory__c = false,
                        Active_for_Scenario__c = false,
                        Active_for_Custom_Factory__c = true,
                        SObject_API_Name__c = 'Account',
                        Field_API_Name__c = 'Description',
                        Field_Value__c = 'desc'
                )
        });
        Account acc = (Account) TestDataFactoryDefaultSettings.getDefaults(Account.SObjectType, true, false);
        System.assertEquals(null, acc.Description);
        acc = (Account) TestDataFactoryDefaultSettings.getDefaults(Account.SObjectType, false, false);
        System.assertEquals('desc', acc.Description);
        acc = (Account) TestDataFactoryDefaultSettings.getDefaults(Account.SObjectType, false, true);
        System.assertEquals(null, acc.Description);
    }
    @IsTest
    static void testGetDefaults_activeForScenario() {
        TestDataFactoryDefaultSettings.sObjNameToSettings.put('Account', new List<Test_Data_Factory_Default__mdt>{
                new Test_Data_Factory_Default__mdt(
                        Active_for_Default_Factory__c = false,
                        Active_for_Scenario__c = true,
                        Active_for_Custom_Factory__c = false,
                        SObject_API_Name__c = 'Account',
                        Field_API_Name__c = 'Description',
                        Field_Value__c = 'desc'
                )
        });
        Account acc = (Account) TestDataFactoryDefaultSettings.getDefaults(Account.SObjectType, true, false);
        System.assertEquals(null, acc.Description);
        acc = (Account) TestDataFactoryDefaultSettings.getDefaults(Account.SObjectType, false, false);
        System.assertEquals(null, acc.Description);
        acc = (Account) TestDataFactoryDefaultSettings.getDefaults(Account.SObjectType, false, true);
        System.assertEquals('desc', acc.Description);
    }
    @IsTest
    static void testGetDefaults_exceptions() {
        TestDataFactoryDefaultSettings.sObjNameToSettings.put('Account', new List<Test_Data_Factory_Default__mdt>{
                new Test_Data_Factory_Default__mdt(
                        DeveloperName = 'account',
                        Active_for_Default_Factory__c = true,
                        Active_for_Scenario__c = false,
                        Active_for_Custom_Factory__c = false,
                        SObject_API_Name__c = 'xyz',
                        Field_API_Name__c = 'Description',
                        Field_Value__c = '1'
                )
        });
        TestDataFactoryDefaultSettings.sObjNameToSettings.put('Contact', new List<Test_Data_Factory_Default__mdt>{
                new Test_Data_Factory_Default__mdt(
                        DeveloperName = 'contact',
                        Active_for_Default_Factory__c = true,
                        Active_for_Scenario__c = false,
                        Active_for_Custom_Factory__c = false,
                        SObject_API_Name__c = 'Contact',
                        Field_API_Name__c = 'xyz',
                        Field_Value__c = '1'
                )
        });
        try {
            TestDataFactoryDefaultSettings.getDefaults(Account.SObjectType, true, false);
        } catch (TestDataFactoryException e) {
            System.assert(e.getMessage().contains('Invalid SObject_API_Name__c.'));
        }
        try {
            TestDataFactoryDefaultSettings.getDefaults(Contact.SObjectType, true, false);
        } catch (TestDataFactoryException e) {
            System.assert(e.getMessage().contains('Invalid Field_API_Name__c.'));
        }
    }
}