src/main/default/objects/Test_Data_Factory_Default__mdt/Test_Data_Factory_Default__mdt.object-meta.xml
<CustomObject>
    <description>Configure default values for SObject Factories and Scenarios.
These default values work even when SObjectFactory and SObjectFactoryScenario are not implemented.
Note that these values can be overwritten by createDefaults method.</description>
    <label>Test Data Factory Default</label>
    <pluralLabel>Test Data Factory Defaults</pluralLabel>
</CustomObject>

src/main/core/objects/Test_Data_Factory_Default__mdt/fields/Active_for_Custom_Factory__c.field-meta.xml
<CustomField>
    <fullName>Active_for_Custom_Factory__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This default value will be used when an SObject Factory is implemented.</description>
    <inlineHelpText>This default value will be used when an SObject Factory is implemented.</inlineHelpText>
    <label>Active for Custom Factory</label>
    <type>Checkbox</type>
</CustomField>

src/main/core/objects/Test_Data_Factory_Default__mdt/fields/Active_for_Default_Factory__c.field-meta.xml
<CustomField>
    <fullName>Active_for_Default_Factory__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This default value will be used when an SObject Factory is not implemented.</description>
    <inlineHelpText>This default value will be used when an SObject Factory is not implemented.</inlineHelpText>
    <label>Active for Default Factory</label>
    <type>Checkbox</type>
</CustomField>

src/main/core/objects/Test_Data_Factory_Default__mdt/fields/Active_for_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Active_for_Scenario__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This default value will be used when a SObjectFactoryScenario is used.</description>
    <inlineHelpText>This default value will be used when a SObjectFactoryScenario is used.</inlineHelpText>
    <label>Active for Scenario</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Test_Data_Factory_Default__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>65</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/core/objects/Test_Data_Factory_Default__mdt/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <description>The default value. The data type will be determined automatically based on the field API name.</description>
    <inlineHelpText>The default value. The data type will be determined automatically based on the field API name.</inlineHelpText>
    <label>Field Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Test_Data_Factory_Default__mdt/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <label>SObject API Name</label>
    <length>43</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/core/classes/TestDataFactoryDefaultSettings.cls
/**
 * @author Ondrej Kratochvil
 * @date 2021-10-16
 */
@IsTest
public without sharing class TestDataFactoryDefaultSettings {
    @TestVisible
    private static final Map<String, List<Test_Data_Factory_Default__mdt>> sObjNameToSettings = new Map<String, List<Test_Data_Factory_Default__mdt>>();
    public static List<Test_Data_Factory_Default__mdt> getValues(String sObjName) {
        if (!sObjNameToSettings.containsKey(sObjName)) {
            List<Test_Data_Factory_Default__mdt> settings = [
                    SELECT
                            DeveloperName,
                            Active_for_Custom_Factory__c,
                            Active_for_Default_Factory__c,
                            Active_for_Scenario__c,
                            Field_API_Name__c,
                            SObject_API_Name__c,
                            Field_Value__c
                    FROM Test_Data_Factory_Default__mdt
                    WHERE SObject_API_Name__c = :sObjName
            ];
            sObjNameToSettings.put(sObjName, settings);
        }
        return sObjNameToSettings.get(sObjName);
    }

    public static SObject getDefaults(SObjectType sObjectType, Boolean isDefaultFactory, Boolean isScenario) {
        SObject defaults = sObjectType.newSObject();
        String sObjName = sObjectType?.getDescribe()?.getName();
        List<Test_Data_Factory_Default__mdt> settings = TestDataFactoryDefaultSettings.getValues(sObjName);
        for (Test_Data_Factory_Default__mdt setting : settings) {
            if ((isScenario && setting.Active_for_Scenario__c) ||
                    (!isScenario && isDefaultFactory && setting.Active_for_Default_Factory__c) ||
                    (!isScenario && !isDefaultFactory && setting.Active_for_Custom_Factory__c)) {
                SObjectType sObjType = SObjectUtils.globalDescribe.get(setting.SObject_API_Name__c);
                if (sObjType == null) {
                    throw new TestDataFactoryException('Invalid SObject_API_Name__c. Check your Test_Data_Factory_Default__mdt record: ' + setting.DeveloperName);
                }
                DescribeFieldResult dfr = SObjectUtils.getDescribeFieldResult(sObjType, setting.Field_API_Name__c);
                if (dfr == null) {
                    throw new TestDataFactoryException('Invalid Field_API_Name__c. Check your Test_Data_Factory_Default__mdt record: ' + setting.DeveloperName);
                }
                try {
                    Object fieldValue = SObjectUtils.parseFieldValue(sObjType, setting.Field_API_Name__c, setting.Field_Value__c);
                    defaults.put(setting.Field_API_Name__c, fieldValue);
                } catch (SObjectException e) {
                    throw new TestDataFactoryException('Unsupported data type. Check your Test_Data_Factory_Default__mdt record: ' + setting.DeveloperName, e);
                }
            }
        }
        return defaults;
    }
}